### ISSUE TITLE
Version wrapper

### ISSUE THREAD

**Issue by wbagdon** [naeramarth7/clean-greader#15]
What I've started doing now is not adding the version field to the css file and instead creating a version wrapper, rather than a symbolic link.

The wrapper sits in the 'themes' folder and just contains

```
/* supports-version:17.1 */

@import "clean-greader/clean-greader.css";
```

The clean-greader.css file doesn't contain any version info this way and it's easily maintainable by the user.
What do you think about this as a solution for maintaining between TT-RSS version updates?

**Comment by naeramarth7** [comment]
Sorry for answering that late - was on vacation. Anyway, I appreciate your suggestion!

So you would actually skip the following line on installation and therefore create the file manually using the mentioned content, where the user has to enter his tt-rss version manually?

```bash
ln -s ./clean-greader/clean-greader.css ./clean-greader.css
```

Sounds reasonable, since users don't have to wait for a version bump in the repo. Looking forward for a PR (:

**Comment by wbagdon** [comment]
Coincidentally I was on vacation when you responded 😄 
PR #16 created
Let me know if it's ok or needs some work

**Comment by naeramarth7** [comment]
@wbagdon  Thanks, mate!
